In [2]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras import layers,models,losses,initializers,metrics,regularizers,optimizers
from tensorflow.keras.optimizers import Adam
import numpy as np
import pandas as pd

In [3]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
print(x_train.shape,y_train.shape,x_test[0][0].shape)
y=x_test.shape
x_train=x_train.reshape(60000,28,28,1)
X_test=x_test.reshape(y[0],28,28,1)

(60000, 28, 28) (60000,) (28,)


In [4]:
hwir=models.Sequential()

hwir.add(layers.Conv2D(32,3,padding='same',activation='relu',input_shape=(28,28,1)))
hwir.add(layers.Flatten())
hwir.add(layers.Dense(10,activation='softmax'))

hwir.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 32)        320       
_________________________________________________________________
flatten (Flatten)            (None, 25088)             0         
_________________________________________________________________
dense (Dense)                (None, 10)                250890    
Total params: 251,210
Trainable params: 251,210
Non-trainable params: 0
_________________________________________________________________


In [43]:
hwir.compile(loss=losses.sparse_categorical_crossentropy,optimizer='Adam',metrics=['accuracy'])

In [44]:
hwir.fit(x_train,y_train,epochs=10)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 20s 326us/sample - loss: 0.6552 - accuracy: 0.9420
Epoch 2/10
60000/60000 [==============================] - 16s 271us/sample - loss: 0.0756 - accuracy: 0.9772
Epoch 3/10
60000/60000 [==============================] - 11s 190us/sample - loss: 0.0664 - accuracy: 0.9793
Epoch 4/10
60000/60000 [==============================] - 12s 207us/sample - loss: 0.0510 - accuracy: 0.9849
Epoch 5/10
60000/60000 [==============================] - 14s 237us/sample - loss: 0.0439 - accuracy: 0.9865
Epoch 6/10
60000/60000 [==============================] - 14s 235us/sample - loss: 0.0339 - accuracy: 0.9906
Epoch 7/10
60000/60000 [==============================] - 14s 239us/sample - loss: 0.0313 - accuracy: 0.9910
Epoch 8/10
60000/60000 [==============================] - 14s 238us/sample - loss: 0.0237 - accuracy: 0.9934
Epoch 9/10
60000/60000 [==============================] - 14s 240us/sample - loss: 0.0238 - accuracy: 0.9

In [45]:
hwir.evaluate(X_test,y_test)

10000/10000 [==============================] - 1s 74us/sample - loss: 0.3005 - accuracy: 0.9705


[0.3005469662775009, 0.9705]

In [48]:
y_hat=hwir.predict_classes(X_test)
y_hat

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [47]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_hat)

0.9705

In [49]:
c=0
for i in range(len(y_test)):
    if y_test[i]==y_hat[i]:
        c=c+1

c

9705

In [15]:
import cv2
img= cv2.imread('test_images/3_1.png',0)
print(np.array(img).shape)
img1=cv2.resize(img,(28,28),interpolation = cv2.INTER_AREA)
img1=cv2.bitwise_not(img1)
test=np.asarray(img1)
test=test.reshape(1,28,28,1)
print(img1)
s=cv2.imshow('image',img1)
cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows()

(237, 237)
[[  7  30  30  30  30  30  30  30  30  30  30  30  30  30  30  30  30  30
   30  30  30  30  30  30  30  30  30  10]
 [ 30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0  30]
 [ 30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0  30]
 [ 30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0  30]
 [ 30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0  30]
 [ 30   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0  30]
 [ 30   0   0   0   0   0  51  90  53  34  34  34  34  34  31  16   3   1
    0   0   0   0   0   0   0   0   0  30]
 [ 30   0   0   0   0   0  93 198 192 183 183 183 183 183 180 155 118  31
    2   0   0   0   0   0   0   0   0  30]
 [ 30   0   0   0   0   0  31 107 160 197 211 211 211

In [14]:
hwir.predict_classes([test])

array([1], dtype=int64)

In [11]:
x_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  